// Code generated by MockGen. DO NOT EDIT.
// Source: httpclient/httpclient.go
//
// Generated by this command:
//
//	mockgen --package mocks --source=httpclient/httpclient.go --destination=httpclient/mocks/mock_httpclient.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	httpclient "github.com/fatkulnurk/foundation/httpclient"
	gomock "go.uber.org/mock/gomock"
)

// MockHttpClient is a mock of HttpClient interface.
type MockHttpClient struct {
	ctrl     *gomock.Controller
	recorder *MockHttpClientMockRecorder
	isgomock struct{}
}

// MockHttpClientMockRecorder is the mock recorder for MockHttpClient.
type MockHttpClientMockRecorder struct {
	mock *MockHttpClient
}

// NewMockHttpClient creates a new mock instance.
func NewMockHttpClient(ctrl *gomock.Controller) *MockHttpClient {
	mock := &MockHttpClient{ctrl: ctrl}
	mock.recorder = &MockHttpClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpClient) EXPECT() *MockHttpClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockHttpClient) Delete(url string) *httpclient.Request {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", url)
	ret0, _ := ret[0].(*httpclient.Request)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockHttpClientMockRecorder) Delete(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHttpClient)(nil).Delete), url)
}

// Get mocks base method.
func (m *MockHttpClient) Get(url string) *httpclient.Request {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", url)
	ret0, _ := ret[0].(*httpclient.Request)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockHttpClientMockRecorder) Get(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHttpClient)(nil).Get), url)
}

// NewRequest mocks base method.
func (m *MockHttpClient) NewRequest() *httpclient.Request {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRequest")
	ret0, _ := ret[0].(*httpclient.Request)
	return ret0
}

// NewRequest indicates an expected call of NewRequest.
func (mr *MockHttpClientMockRecorder) NewRequest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRequest", reflect.TypeOf((*MockHttpClient)(nil).NewRequest))
}

// Patch mocks base method.
func (m *MockHttpClient) Patch(url string) *httpclient.Request {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", url)
	ret0, _ := ret[0].(*httpclient.Request)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockHttpClientMockRecorder) Patch(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockHttpClient)(nil).Patch), url)
}

// Post mocks base method.
func (m *MockHttpClient) Post(url string) *httpclient.Request {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", url)
	ret0, _ := ret[0].(*httpclient.Request)
	return ret0
}

// Post indicates an expected call of Post.
func (mr *MockHttpClientMockRecorder) Post(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockHttpClient)(nil).Post), url)
}

// Put mocks base method.
func (m *MockHttpClient) Put(url string) *httpclient.Request {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", url)
	ret0, _ := ret[0].(*httpclient.Request)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockHttpClientMockRecorder) Put(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockHttpClient)(nil).Put), url)
}
