// Code generated by MockGen. DO NOT EDIT.
// Source: storage/storage.go
//
// Generated by this command:
//
//	mockgen --package mocks --source=storage/storage.go --destination=storage/mocks/mock_storage.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	storage "github.com/fatkulnurk/foundation/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Copy mocks base method.
func (m *MockStorage) Copy(ctx context.Context, sourcePath, destinationPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy", ctx, sourcePath, destinationPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Copy indicates an expected call of Copy.
func (mr *MockStorageMockRecorder) Copy(ctx, sourcePath, destinationPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*MockStorage)(nil).Copy), ctx, sourcePath, destinationPath)
}

// Delete mocks base method.
func (m *MockStorage) Delete(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStorageMockRecorder) Delete(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStorage)(nil).Delete), ctx, path)
}

// Directories mocks base method.
func (m *MockStorage) Directories(ctx context.Context, dir string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Directories", ctx, dir)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Directories indicates an expected call of Directories.
func (mr *MockStorageMockRecorder) Directories(ctx, dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Directories", reflect.TypeOf((*MockStorage)(nil).Directories), ctx, dir)
}

// Exists mocks base method.
func (m *MockStorage) Exists(ctx context.Context, path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockStorageMockRecorder) Exists(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockStorage)(nil).Exists), ctx, path)
}

// File mocks base method.
func (m *MockStorage) File(ctx context.Context, path string, expiryTempUrl *time.Duration) (*storage.FileStorage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "File", ctx, path, expiryTempUrl)
	ret0, _ := ret[0].(*storage.FileStorage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// File indicates an expected call of File.
func (mr *MockStorageMockRecorder) File(ctx, path, expiryTempUrl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "File", reflect.TypeOf((*MockStorage)(nil).File), ctx, path, expiryTempUrl)
}

// Files mocks base method.
func (m *MockStorage) Files(ctx context.Context, dir string, expiryTempUrl *time.Duration) ([]storage.FileStorage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Files", ctx, dir, expiryTempUrl)
	ret0, _ := ret[0].([]storage.FileStorage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Files indicates an expected call of Files.
func (mr *MockStorageMockRecorder) Files(ctx, dir, expiryTempUrl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Files", reflect.TypeOf((*MockStorage)(nil).Files), ctx, dir, expiryTempUrl)
}

// Get mocks base method.
func (m *MockStorage) Get(ctx context.Context, path string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStorageMockRecorder) Get(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStorage)(nil).Get), ctx, path)
}

// Move mocks base method.
func (m *MockStorage) Move(ctx context.Context, sourcePath, destinationPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Move", ctx, sourcePath, destinationPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Move indicates an expected call of Move.
func (mr *MockStorageMockRecorder) Move(ctx, sourcePath, destinationPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Move", reflect.TypeOf((*MockStorage)(nil).Move), ctx, sourcePath, destinationPath)
}

// Upload mocks base method.
func (m *MockStorage) Upload(ctx context.Context, input storage.UploadInput) (*storage.UploadOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, input)
	ret0, _ := ret[0].(*storage.UploadOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockStorageMockRecorder) Upload(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockStorage)(nil).Upload), ctx, input)
}
