// Code generated by MockGen. DO NOT EDIT.
// Source: queue/queue.go
//
// Generated by this command:
//
//	mockgen --package mocks --source=queue/queue.go --destination=queue/mocks/mock_queue.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	queue "github.com/fatkulnurk/foundation/queue"
	gomock "go.uber.org/mock/gomock"
)

// MockQueue is a mock of Queue interface.
type MockQueue struct {
	ctrl     *gomock.Controller
	recorder *MockQueueMockRecorder
	isgomock struct{}
}

// MockQueueMockRecorder is the mock recorder for MockQueue.
type MockQueueMockRecorder struct {
	mock *MockQueue
}

// NewMockQueue creates a new mock instance.
func NewMockQueue(ctrl *gomock.Controller) *MockQueue {
	mock := &MockQueue{ctrl: ctrl}
	mock.recorder = &MockQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueue) EXPECT() *MockQueueMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockQueue) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockQueueMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockQueue)(nil).Close))
}

// Enqueue mocks base method.
func (m *MockQueue) Enqueue(ctx context.Context, taskName string, payload any, opts ...queue.Option) (*queue.OutputEnqueue, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, taskName, payload}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Enqueue", varargs...)
	ret0, _ := ret[0].(*queue.OutputEnqueue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockQueueMockRecorder) Enqueue(ctx, taskName, payload any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, taskName, payload}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockQueue)(nil).Enqueue), varargs...)
}

// GetTaskInfo mocks base method.
func (m *MockQueue) GetTaskInfo(ctx context.Context, taskID string) (*queue.TaskInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskInfo", ctx, taskID)
	ret0, _ := ret[0].(*queue.TaskInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskInfo indicates an expected call of GetTaskInfo.
func (mr *MockQueueMockRecorder) GetTaskInfo(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskInfo", reflect.TypeOf((*MockQueue)(nil).GetTaskInfo), ctx, taskID)
}

// MockWorker is a mock of Worker interface.
type MockWorker struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerMockRecorder
	isgomock struct{}
}

// MockWorkerMockRecorder is the mock recorder for MockWorker.
type MockWorkerMockRecorder struct {
	mock *MockWorker
}

// NewMockWorker creates a new mock instance.
func NewMockWorker(ctrl *gomock.Controller) *MockWorker {
	mock := &MockWorker{ctrl: ctrl}
	mock.recorder = &MockWorkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorker) EXPECT() *MockWorkerMockRecorder {
	return m.recorder
}

// GetTaskID mocks base method.
func (m *MockWorker) GetTaskID(ctx context.Context) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskID", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetTaskID indicates an expected call of GetTaskID.
func (mr *MockWorkerMockRecorder) GetTaskID(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskID", reflect.TypeOf((*MockWorker)(nil).GetTaskID), ctx)
}

// GetTaskInfo mocks base method.
func (m *MockWorker) GetTaskInfo(ctx context.Context, taskID string) (*queue.TaskInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskInfo", ctx, taskID)
	ret0, _ := ret[0].(*queue.TaskInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskInfo indicates an expected call of GetTaskInfo.
func (mr *MockWorkerMockRecorder) GetTaskInfo(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskInfo", reflect.TypeOf((*MockWorker)(nil).GetTaskInfo), ctx, taskID)
}

// Register mocks base method.
func (m *MockWorker) Register(taskType string, handler queue.Handler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", taskType, handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockWorkerMockRecorder) Register(taskType, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockWorker)(nil).Register), taskType, handler)
}

// RegisterWithMiddleware mocks base method.
func (m *MockWorker) RegisterWithMiddleware(taskType string, handler queue.Handler, middleware ...queue.MiddlewareFunc) error {
	m.ctrl.T.Helper()
	varargs := []any{taskType, handler}
	for _, a := range middleware {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RegisterWithMiddleware", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterWithMiddleware indicates an expected call of RegisterWithMiddleware.
func (mr *MockWorkerMockRecorder) RegisterWithMiddleware(taskType, handler any, middleware ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{taskType, handler}, middleware...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterWithMiddleware", reflect.TypeOf((*MockWorker)(nil).RegisterWithMiddleware), varargs...)
}

// Start mocks base method.
func (m *MockWorker) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockWorkerMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockWorker)(nil).Start))
}

// Stop mocks base method.
func (m *MockWorker) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockWorkerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockWorker)(nil).Stop))
}
