// Code generated by MockGen. DO NOT EDIT.
// Source: view/view.go
//
// Generated by this command:
//
//	mockgen --package mocks --source=view/view.go --destination=view/mocks/mock_view.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	view "github.com/fatkulnurk/foundation/view"
	gomock "go.uber.org/mock/gomock"
)

// MockView is a mock of View interface.
type MockView struct {
	ctrl     *gomock.Controller
	recorder *MockViewMockRecorder
	isgomock struct{}
}

// MockViewMockRecorder is the mock recorder for MockView.
type MockViewMockRecorder struct {
	mock *MockView
}

// NewMockView creates a new mock instance.
func NewMockView(ctrl *gomock.Controller) *MockView {
	mock := &MockView{ctrl: ctrl}
	mock.recorder = &MockViewMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockView) EXPECT() *MockViewMockRecorder {
	return m.recorder
}

// AddFunc mocks base method.
func (m *MockView) AddFunc(name string, fn any) view.View {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFunc", name, fn)
	ret0, _ := ret[0].(view.View)
	return ret0
}

// AddFunc indicates an expected call of AddFunc.
func (mr *MockViewMockRecorder) AddFunc(name, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFunc", reflect.TypeOf((*MockView)(nil).AddFunc), name, fn)
}

// ClearCache mocks base method.
func (m *MockView) ClearCache() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearCache")
}

// ClearCache indicates an expected call of ClearCache.
func (mr *MockViewMockRecorder) ClearCache() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearCache", reflect.TypeOf((*MockView)(nil).ClearCache))
}

// Render mocks base method.
func (m *MockView) Render(ctx context.Context, name string, data any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Render", ctx, name, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Render indicates an expected call of Render.
func (mr *MockViewMockRecorder) Render(ctx, name, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockView)(nil).Render), ctx, name, data)
}

// RenderWithLayout mocks base method.
func (m *MockView) RenderWithLayout(ctx context.Context, layout, name string, data any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderWithLayout", ctx, layout, name, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenderWithLayout indicates an expected call of RenderWithLayout.
func (mr *MockViewMockRecorder) RenderWithLayout(ctx, layout, name, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderWithLayout", reflect.TypeOf((*MockView)(nil).RenderWithLayout), ctx, layout, name, data)
}

// SetGlobal mocks base method.
func (m *MockView) SetGlobal(key string, value any) view.View {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGlobal", key, value)
	ret0, _ := ret[0].(view.View)
	return ret0
}

// SetGlobal indicates an expected call of SetGlobal.
func (mr *MockViewMockRecorder) SetGlobal(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGlobal", reflect.TypeOf((*MockView)(nil).SetGlobal), key, value)
}
