// Code generated by MockGen. DO NOT EDIT.
// Source: httprouter/router.go
//
// Generated by this command:
//
//	mockgen --package mocks --source=httprouter/router.go --destination=httprouter/mocks/mock_router.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	httprouter "github.com/fatkulnurk/foundation/httprouter"
	gomock "go.uber.org/mock/gomock"
)

// MockHttpRouter is a mock of HttpRouter interface.
type MockHttpRouter struct {
	ctrl     *gomock.Controller
	recorder *MockHttpRouterMockRecorder
	isgomock struct{}
}

// MockHttpRouterMockRecorder is the mock recorder for MockHttpRouter.
type MockHttpRouterMockRecorder struct {
	mock *MockHttpRouter
}

// NewMockHttpRouter creates a new mock instance.
func NewMockHttpRouter(ctrl *gomock.Controller) *MockHttpRouter {
	mock := &MockHttpRouter{ctrl: ctrl}
	mock.recorder = &MockHttpRouterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpRouter) EXPECT() *MockHttpRouterMockRecorder {
	return m.recorder
}

// DELETE mocks base method.
func (m *MockHttpRouter) DELETE(path string, h http.HandlerFunc, mws ...func(http.Handler) http.Handler) {
	m.ctrl.T.Helper()
	varargs := []any{path, h}
	for _, a := range mws {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "DELETE", varargs...)
}

// DELETE indicates an expected call of DELETE.
func (mr *MockHttpRouterMockRecorder) DELETE(path, h any, mws ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{path, h}, mws...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DELETE", reflect.TypeOf((*MockHttpRouter)(nil).DELETE), varargs...)
}

// GET mocks base method.
func (m *MockHttpRouter) GET(path string, h http.HandlerFunc, mws ...func(http.Handler) http.Handler) {
	m.ctrl.T.Helper()
	varargs := []any{path, h}
	for _, a := range mws {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "GET", varargs...)
}

// GET indicates an expected call of GET.
func (mr *MockHttpRouterMockRecorder) GET(path, h any, mws ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{path, h}, mws...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GET", reflect.TypeOf((*MockHttpRouter)(nil).GET), varargs...)
}

// Group mocks base method.
func (m *MockHttpRouter) Group(prefix string, fn func(httprouter.HttpRouter)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Group", prefix, fn)
}

// Group indicates an expected call of Group.
func (mr *MockHttpRouterMockRecorder) Group(prefix, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Group", reflect.TypeOf((*MockHttpRouter)(nil).Group), prefix, fn)
}

// Handle mocks base method.
func (m *MockHttpRouter) Handle(pattern string, h http.Handler, mws ...func(http.Handler) http.Handler) {
	m.ctrl.T.Helper()
	varargs := []any{pattern, h}
	for _, a := range mws {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Handle", varargs...)
}

// Handle indicates an expected call of Handle.
func (mr *MockHttpRouterMockRecorder) Handle(pattern, h any, mws ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{pattern, h}, mws...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockHttpRouter)(nil).Handle), varargs...)
}

// HandleFunc mocks base method.
func (m *MockHttpRouter) HandleFunc(pattern string, h http.HandlerFunc, mws ...func(http.Handler) http.Handler) {
	m.ctrl.T.Helper()
	varargs := []any{pattern, h}
	for _, a := range mws {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "HandleFunc", varargs...)
}

// HandleFunc indicates an expected call of HandleFunc.
func (mr *MockHttpRouterMockRecorder) HandleFunc(pattern, h any, mws ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{pattern, h}, mws...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleFunc", reflect.TypeOf((*MockHttpRouter)(nil).HandleFunc), varargs...)
}

// PATCH mocks base method.
func (m *MockHttpRouter) PATCH(path string, h http.HandlerFunc, mws ...func(http.Handler) http.Handler) {
	m.ctrl.T.Helper()
	varargs := []any{path, h}
	for _, a := range mws {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "PATCH", varargs...)
}

// PATCH indicates an expected call of PATCH.
func (mr *MockHttpRouterMockRecorder) PATCH(path, h any, mws ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{path, h}, mws...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PATCH", reflect.TypeOf((*MockHttpRouter)(nil).PATCH), varargs...)
}

// POST mocks base method.
func (m *MockHttpRouter) POST(path string, h http.HandlerFunc, mws ...func(http.Handler) http.Handler) {
	m.ctrl.T.Helper()
	varargs := []any{path, h}
	for _, a := range mws {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "POST", varargs...)
}

// POST indicates an expected call of POST.
func (mr *MockHttpRouterMockRecorder) POST(path, h any, mws ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{path, h}, mws...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "POST", reflect.TypeOf((*MockHttpRouter)(nil).POST), varargs...)
}

// PUT mocks base method.
func (m *MockHttpRouter) PUT(path string, h http.HandlerFunc, mws ...func(http.Handler) http.Handler) {
	m.ctrl.T.Helper()
	varargs := []any{path, h}
	for _, a := range mws {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "PUT", varargs...)
}

// PUT indicates an expected call of PUT.
func (mr *MockHttpRouterMockRecorder) PUT(path, h any, mws ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{path, h}, mws...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PUT", reflect.TypeOf((*MockHttpRouter)(nil).PUT), varargs...)
}

// ServeHTTP mocks base method.
func (m *MockHttpRouter) ServeHTTP(arg0 http.ResponseWriter, arg1 *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ServeHTTP", arg0, arg1)
}

// ServeHTTP indicates an expected call of ServeHTTP.
func (mr *MockHttpRouterMockRecorder) ServeHTTP(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServeHTTP", reflect.TypeOf((*MockHttpRouter)(nil).ServeHTTP), arg0, arg1)
}

// Static mocks base method.
func (m *MockHttpRouter) Static(prefix, dir string, mws ...func(http.Handler) http.Handler) {
	m.ctrl.T.Helper()
	varargs := []any{prefix, dir}
	for _, a := range mws {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Static", varargs...)
}

// Static indicates an expected call of Static.
func (mr *MockHttpRouterMockRecorder) Static(prefix, dir any, mws ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{prefix, dir}, mws...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Static", reflect.TypeOf((*MockHttpRouter)(nil).Static), varargs...)
}

// Use mocks base method.
func (m *MockHttpRouter) Use(mw func(http.Handler) http.Handler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Use", mw)
}

// Use indicates an expected call of Use.
func (mr *MockHttpRouterMockRecorder) Use(mw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Use", reflect.TypeOf((*MockHttpRouter)(nil).Use), mw)
}
