// Code generated by MockGen. DO NOT EDIT.
// Source: container/container.go
//
// Generated by this command:
//
//	mockgen --package mocks --source=container/container.go --destination=container/mocks/mock_container.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockContainer is a mock of Container interface.
type MockContainer struct {
	ctrl     *gomock.Controller
	recorder *MockContainerMockRecorder
	isgomock struct{}
}

// MockContainerMockRecorder is the mock recorder for MockContainer.
type MockContainerMockRecorder struct {
	mock *MockContainer
}

// NewMockContainer creates a new mock instance.
func NewMockContainer(ctrl *gomock.Controller) *MockContainer {
	mock := &MockContainer{ctrl: ctrl}
	mock.recorder = &MockContainerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContainer) EXPECT() *MockContainerMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockContainer) Get(name string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", name)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockContainerMockRecorder) Get(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockContainer)(nil).Get), name)
}

// Has mocks base method.
func (m *MockContainer) Has(name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Has", name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Has indicates an expected call of Has.
func (mr *MockContainerMockRecorder) Has(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Has", reflect.TypeOf((*MockContainer)(nil).Has), name)
}

// MustGet mocks base method.
func (m *MockContainer) MustGet(name string) any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MustGet", name)
	ret0, _ := ret[0].(any)
	return ret0
}

// MustGet indicates an expected call of MustGet.
func (mr *MockContainerMockRecorder) MustGet(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MustGet", reflect.TypeOf((*MockContainer)(nil).MustGet), name)
}

// Set mocks base method.
func (m *MockContainer) Set(name string, service any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", name, service)
}

// Set indicates an expected call of Set.
func (mr *MockContainerMockRecorder) Set(name, service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockContainer)(nil).Set), name, service)
}
